### PR TITLE
add hash to webpack bundle

### PR DESCRIPTION
**Pull request by californianseabass**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/totx/62)

### CODE REVIEW

**Comment by danvk** [comment]
Does `yarn develop -- transit` still work? I get this error:

```
$ yarn develop -- transit
yarn run v1.3.2
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ ./scripts/develop.sh transit
[nodemon] 1.15.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server/*.ts
[nodemon] starting `ts-node packages/transit/server/server.ts`
 10% 0/1 build modules
[at-loader] Using typescript@2.7.2 from typescript and "tsconfig.json" from /Users/danvk/github/ttx/tsconfig.json.

Starting up...
Dev mode
Using routing server at http://router-ttx

/Users/danvk/github/ttx/node_modules/find/index.js:41
    return new Error(name + ' does not exist.');
           ^
Error: /Users/danvk/github/ttx/packages/transit/server/../static does not exist.
    at Object.notExist (/Users/danvk/github/ttx/node_modules/find/index.js:41:12)
    at traverseSync (/Users/danvk/github/ttx/node_modules/find/index.js:224:38)
    at Object.find.(anonymous function) [as fileSync] (/Users/danvk/github/ttx/node_modules/find/index.js:374:5)
    at createCache (/Users/danvk/github/ttx/node_modules/connect-gzip-static/lib/gzip-static.js:21:8)
    at module.exports (/Users/danvk/github/ttx/node_modules/connect-gzip-static/lib/gzip-static.js:29:32)
    at Object.<anonymous> (/Users/danvk/github/ttx/packages/transit/server/server.ts:84:3)
    at Module._compile (module.js:660:30)
    at Module.m._compile (/Users/danvk/github/ttx/node_modules/ts-node/src/index.ts:400:23)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/danvk/github/ttx/node_modules/ts-node/src/index.ts:403:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by danvk** [comment]
:lgtm:

So what was the issue I was running into? Please thoroughly test this on staging before deploying to prod.

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved.

---

*[package.json, line 92 at r1](https://reviewable.io/reviews/sidewalklabs/totx/62#-LC4KLcW6cGg_6dB5-Fh:-LC4KLcW6cGg_6dB5-Fi:b-l9hmuu) ([raw file](https://github.com/sidewalklabs/totx/blob/2e66ecc3e7945d3f4bfe087c7abd1bdc6132e902/package.json#L92)):*
> ```JSON
>     "prettier-test": "./scripts/prettier.sh --list-different",
>     "lint": "tslint --project tsconfig.json",
>     "serve": "yarn webpack && ts-node packages/transit/server/server.ts",
> ```

remove this, we explicitly run `yarn webpack` in our `Dockerfile`:
https://github.com/sidewalklabs/totx/blob/adf4ddfb756e0d06abc106321d2b596e289c20ec/Dockerfile#L20

---

*[scripts/develop.sh, line 22 at r1](https://reviewable.io/reviews/sidewalklabs/totx/62#-LC4K6Og377AqqHw6CYx:-LC4K6Og377AqqHw6CYy:b-tp3tm4) ([raw file](https://github.com/sidewalklabs/totx/blob/2e66ecc3e7945d3f4bfe087c7abd1bdc6132e902/scripts/develop.sh#L22)):*
> ```Shell
> 
> webpack --config $webpack_config
> webpack --config $webpack_config --progress --colors --watch &
> ```

Why do we need to run webpack twice? (`webpack --watch` should do the same thing as `webpack` until files change.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/totx/62#-:-LC4Ka8A8aR9MC3Isapa:b-vcoqlx)*

**Comment by samaratrilling** [comment]
Review status: 0 of 27 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.gitignore, line 11 at r1](https://reviewable.io/reviews/sidewalklabs/totx/62#-LC4Lm6vBc9_uJcs2Pgl:-LC4Lm6vBc9_uJcs2Pgm:b-ns420o) ([raw file](https://github.com/sidewalklabs/totx/blob/2e66ecc3e7945d3f4bfe087c7abd1bdc6132e902/.gitignore#L11)):*
> ```
> 
> # Generated static files
> packages/transit/static/
> ```

Should we be gitignoring these files? This is where the About page and T&Cs live, so if we make updates to them we'll want that to be picked up by git.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/totx/62)*

**Comment by californianseabass** [comment]
the issue is that yarn watch runs asynchronously and doesn't finish building before ts-node tries to run everything. essentially if you ran it again, it would work

---

Review status: 0 of 27 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[.gitignore, line 11 at r1](https://reviewable.io/reviews/sidewalklabs/totx/62#-LC4Lm6vBc9_uJcs2Pgl:-LC4M74c-9EsT-6HZP7U:b-th0lic) ([raw file](https://github.com/sidewalklabs/totx/blob/2e66ecc3e7945d3f4bfe087c7abd1bdc6132e902/.gitignore#L11)):*
<details><summary><i>Previously, samaratrilling (Samara Trilling) wrote…</i></summary><blockquote>

Should we be gitignoring these files? This is where the About page and T&Cs live, so if we make updates to them we'll want that to be picked up by git.
</blockquote></details>

everything gets bundled into that folder, imo, you shouldn't be mixing a folder with transpiled files and more permanent assests, the issues it raises are the cause of every single comment in this PR

---

*[scripts/develop.sh, line 22 at r1](https://reviewable.io/reviews/sidewalklabs/totx/62#-LC4K6Og377AqqHw6CYx:-LC4Ldys1JeJ35mas4v6:b-9o8hi9) ([raw file](https://github.com/sidewalklabs/totx/blob/2e66ecc3e7945d3f4bfe087c7abd1bdc6132e902/scripts/develop.sh#L22)):*
<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary><blockquote>

Why do we need to run webpack twice? (`webpack --watch` should do the same thing as `webpack` until files change.)
</blockquote></details>

the ampersand runs watch asynchronously

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/totx/62#-:-LC4LrE-A5Yr2bLJQyli:bnl0ldt)*

**Comment by californianseabass** [comment]
Review status: 0 of 27 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[package.json, line 92 at r1](https://reviewable.io/reviews/sidewalklabs/totx/62#-LC4KLcW6cGg_6dB5-Fh:-LC4RB5a2W2ZwiGyWHig:b-896fix) ([raw file](https://github.com/sidewalklabs/totx/blob/2e66ecc3e7945d3f4bfe087c7abd1bdc6132e902/package.json#L92)):*
<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary><blockquote>

remove this, we explicitly run `yarn webpack` in our `Dockerfile`:
https://github.com/sidewalklabs/totx/blob/adf4ddfb756e0d06abc106321d2b596e289c20ec/Dockerfile#L20
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/totx/62)*

**Pull request merged**
