### PR TITLE
Make the presence of Google Analytics optional

### PR DESCRIPTION
**Pull request by joined**
Fixes issue #73

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/totx/74)

### CODE REVIEW

**Comment by danvk** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/totx/74#-:-LGVR6Lm-HYIZmGRRpHV:bnfp4nl)*

**Comment by danvk** [comment]
Thanks @joined! I'll roll this out to production shortly.

**Comment by danvk** [comment]
This should be live on https://totx.sidewalklabs.com. Could you verify that the site works with your ad blocker active? Thanks!

**Comment by joined** [comment]
Yes, can confirm :)

**Pull request merged**
